apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.id }}
  annotations:
    reloader.stakater.com/match: "true"
data:
  {{- range $name, $value := .Values.env }}
  {{ $name }}: "{{ $value }}"
  {{- end }}
