{{ if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-{{ .Values.id }}-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.path }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.id }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: |
      {{ .Release.Namespace }}-{{ .Release.Name }}-{{ .Values.id }}-strip-prefix@kubernetescrd,
      default-compression@kubernetescrd,
      default-ssl-redirect@kubernetescrd
    cert-manager.io/cluster-issuer: {{ .Values.global.ingress.certManager.issuer }}
spec:
  ingressClassName: {{ .Values.global.ingress.class }}
  rules:
    - host: "{{ .Values.global.ingress.fqdn }}"
      http:
        paths:
          - path: {{ .Values.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.id }}
                port:
                  name: web
  tls:
    - hosts:
        - "{{ .Values.global.ingress.fqdn }}"
      secretName: {{ .Release.Name }}-{{ .Values.id }}-ingress-cert
{{ end }}
